FROM java:8
COPY . /Users/sactrek/dockerfiles/Fecha.java
WORKDIR /Users/sactrek/dockerfiles/Fecha.java
RUN javac Fecha.java
CMD ["java", "Fecha"]

FROM java:8
COPY . /Users/sactrek/dockerfiles/Hora.java
WORKDIR /Users/sactrek/dockerfiles/Hora.java
RUN javac Hora.java
CMD ["java", "Hora"]

FROM java:8
COPY . /Users/sactrek/dockerfiles/Numero.java
WORKDIR /Users/sactrek/dockerfiles/Numero.java
RUN javac Numero.java
CMD ["java", "Numero"]
